---

- name: Append the new password and hostname to the file on Ansible Node
  delegate_to: localhost
  ansible.builtin.lineinfile:
    path: "{{ user_pw_rotate_store_file }}"
    line: "{{ inventory_hostname }}, {{ user_pw_rotate_target }}, {{ new_password.stdout }}"
    insertafter: EOF
