---

- name: Check if EPEL repository is installed
  ansible.builtin.command: dnf repolist epel
  register: epel_repo
  changed_when: epel_repo.rc != 0

- name: Exclude epel zabbix packages
  ansible.builtin.template:
    src: epel.repo.j2
    dest: /etc/yum.repos.d/epel.repo
    owner: root
    group: root
    mode: '0600'
  when: epel_repo.rc != 0

- name: Add Zabbix repository
  ansible.builtin.dnf:
    name:
      - https://repo.zabbix.com/zabbix/7.0/centos/9/x86_64/zabbix-release-7.0-4.el9.noarch.rpm
    state: present
    update_cache: true

- name: Install Zabbix agent2 and plugins
  ansible.builtin.dnf:
    name:
      - zabbix-agent2
      - "zabbix-agent2-plugin-*"
    state: present
