---

- name: Install required packages
  ansible.builtin.dnf:
    name:
      - realmd
      - sssd
      - sssd-tools
      - adcli
      - oddjob
      - oddjob-mkhomedir
      - python3-pexpect
    state: present

- name: Enable home directory
  ansible.builtin.command: /bin/bash -c "/usr/bin/authselect select sssd with-mkhomedir --force"
  register: home_folder
  changed_when: home_folder != ""
