---

- name: Updates
  ansible.builtin.import_tasks:
    debian.yml
  when: ansible_os_family == 'Debian'

- name: Updates
  ansible.builtin.import_tasks:
    rhel.yml
  when: ansible_os_family == 'RedHat'
